"""Generate NPC sprite sheets from text-grid pixel art.

Run from the project root (requires Pillow, dev-only):

    python tools/generate_npc_sprites.py

Writes one sheet per human NPC under assets/sprites/npcs/: three 16x30
frames (down, up, left), with right-facing flipped at runtime.

Design notes (Game Bible: scale is a pillar): a human is 30px tall to
Chuck's 14. Talking to one means talking to a pair of boots and trusting
there's a person up there. NPCs don't animate beyond facing — the docks
are tired, and so is everyone on them.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from spritegen import render_sheet

FRAME_W, FRAME_H = 16, 30

PALETTE = {
    ".": (0, 0, 0, 0),
    "H": (74, 52, 38, 255),     # hair / flat cap
    "S": (218, 176, 138, 255),  # skin
    "E": (30, 28, 34, 255),     # eyes
    "O": (110, 104, 66, 255),   # olive work shirt
    "o": (84, 80, 50, 255),     # shirt shadow
    "B": (94, 70, 50, 255),     # trousers
    "b": (56, 44, 36, 255),     # boots
    # Waterdeep guard (same build as the worker — armored, not bigger)
    "M": (138, 140, 150, 255),  # steel helm / mail
    "m": (98, 100, 112, 255),   # steel shadow
    "T": (72, 92, 132, 255),    # city tabard
    "t": (52, 68, 100, 255),    # tabard shadow
    "P": (110, 78, 48, 255),    # spear shaft
    "p": (176, 180, 190, 255),  # spear head
    # Market woman: the worker's exact silhouette in a headscarf and apron.
    "K": (176, 116, 62, 255),   # warm ochre headscarf
    "R": (132, 58, 54, 255),    # muted red blouse
    "r": (94, 42, 44, 255),     # blouse shadow
    "C": (188, 166, 124, 255),  # work apron / skirt
}

WORKER_DOWN = """
....HHHHHHHH....
...HHHHHHHHHH...
...HSSSSSSSSH...
...SSSSSSSSSS...
...SSESSSSESS...
...SSSSSSSSSS...
...SSSSSSSSSS...
....SSSSSSSS....
....OOOOOOOO....
..OOOOOOOOOOOO..
..OOOOOOOOOOOO..
.OOOOOOOOOOOOOO.
.OOoOOOOOOOOoOO.
.OOoOOOOOOOOoOO.
.OOOOOOOOOOOOOO.
.OOOOOOOOOOOOOO.
.SSOOOOOOOOOOSS.
..OOOOOOOOOOOO..
..oOOOOOOOOOOo..
...BBBBBBBBBB...
...BBBBBBBBBB...
...BBBB..BBBB...
...BBBB..BBBB...
...BBBB..BBBB...
...BBBB..BBBB...
...BBBB..BBBB...
...bbbb..bbbb...
...bbbb..bbbb...
..bbbbb..bbbbb..
................
"""

WORKER_UP = """
....HHHHHHHH....
...HHHHHHHHHH...
...HHHHHHHHHH...
...HHHHHHHHHH...
...HHHHHHHHHH...
...SSHHHHHHSS...
...SSSHHHHSSS...
....SSSSSSSS....
....OOOOOOOO....
..OOOOOOOOOOOO..
..OOOOOOOOOOOO..
.OOOOOOOOOOOOOO.
.OOoOOOOOOOOoOO.
.OOoOOOOOOOOoOO.
.OOOOOOOOOOOOOO.
.OOOOOOOOOOOOOO.
.SSOOOOOOOOOOSS.
..OOOOOOOOOOOO..
..oOOOOOOOOOOo..
...BBBBBBBBBB...
...BBBBBBBBBB...
...BBBB..BBBB...
...BBBB..BBBB...
...BBBB..BBBB...
...BBBB..BBBB...
...BBBB..BBBB...
...bbbb..bbbb...
...bbbb..bbbb...
..bbbbb..bbbbb..
................
"""

WORKER_LEFT = """
....HHHHHHHH....
...HHHHHHHHHH...
...SSSSSHHHHH...
...SSSSSHHHHH...
...SESSSHHHHH...
...SSSSSHHHHH...
...SSSSSSHHHH...
....SSSSSSSS....
....OOOOOOOO....
..OOOOOOOOOOOO..
..OOOOOOOOOOOO..
.OOOOOOOOOOOOOO.
.OOoOOOOOOOOoOO.
.OOoOOOOOOOOoOO.
.OOOOOOOOOOOOOO.
.OOOOOOOOOOOOOO.
..SSOOOOOOOOOO..
..OOOOOOOOOOOO..
..oOOOOOOOOOOo..
...BBBBBBBBBB...
...BBBBBBBBBB...
...BBBB..BBBB...
...BBBB..BBBB...
...BBBB..BBBB...
...BBBB..BBBB...
...BBBB..BBBB...
...bbbb..bbbb...
...bbbb..bbbb...
..bbbbb..bbbb...
................
"""

# The guard: the worker's exact silhouette and height (Phase 2 rule —
# humans never get bigger or more detailed), wearing a helm, mail, and
# the city's tabard, with a spear planted at his side.
GUARD_DOWN = """
....MMMMMMMM....
...MMMMMMMMMM...
...MMSSSSSSMM...
...MSSSSSSSSM..P
...MSSESSESSM..P
...MSSSSSSSSM..P
...mSSSSSSSSm..p
....SSSSSSSS...p
....MMMMMMMM...P
..MMTTTTTTTTMM.P
..MMTTTTTTTTMM.P
.MMMTTTTTTTTMMMP
.MMmTTTTTTTTmMMP
.MMmTTTTTTTTmMMP
.MMMTTTTTTTTMMMP
.MMMTTtttttTMMMP
..MMTTTTTTTTMM.P
..MMTTTTTTTTMM.P
...MTTTTTTTTM..P
...MTTTTTTTTM..P
....TTTTTTTT...P
....TTtttTTT...P
....BBBBBBBB...P
....BBBBBBBB...P
....BBB..BBB...P
....BBB..BBB...P
....BBB..BBB...P
....bbb..bbb...P
....bbb..bbb...P
....bbb..bbb...P
"""

GUARD_UP = """
....MMMMMMMM....
...MMMMMMMMMM...
...MMMMMMMMMM...
...MMMMMMMMMM..P
...MMMMMMMMMM..P
...MMMMMMMMMM..P
...mMMMMMMMMm..p
....MMMMMMMM...p
....MMMMMMMM...P
..MMTTTTTTTTMM.P
..MMTTTTTTTTMM.P
.MMMTTTTTTTTMMMP
.MMmTTTTTTTTmMMP
.MMmTTTTTTTTmMMP
.MMMTTTTTTTTMMMP
.MMMTTTTTTTTMMMP
..MMTTTTTTTTMM.P
..MMTTTTTTTTMM.P
...MTTTTTTTTM..P
...MTTTTTTTTM..P
....TTTTTTTT...P
....TTTTTTTT...P
....BBBBBBBB...P
....BBBBBBBB...P
....BBB..BBB...P
....BBB..BBB...P
....BBB..BBB...P
....bbb..bbb...P
....bbb..bbb...P
....bbb..bbb...P
"""

GUARD_LEFT = """
P...MMMMMMMM....
P..MMMMMMMMMM...
P..MMSSSSSSMM...
P..MSSSSSSSSM...
p..MSSESSSSSM...
p..MSSSSSSSSM...
P..mSSSSSSSSm...
P...SSSSSSSS....
P...MMMMMMMM....
P.MMMTTTTTTMMM..
P.MMMTTTTTTMMM..
P.MMMTTTTTTMMM..
P.MMmTTTTTTmMM..
P.MMmTTTTTTmMM..
P.MMMTTTTTTMMM..
P.MMMTTtttTMMM..
P..MMTTTTTTMM...
P..MMTTTTTTMM...
P...MTTTTTTM....
P...MTTTTTTM....
P....TTTTTT.....
P....TTtttT.....
P....BBBBBB.....
P....BBBBBB.....
P....BBBBBB.....
P....BBB.BBB....
P....BBB.BBB....
P....bbb.bbb....
P....bbb.bbb....
P....bbb.bbb....
"""

SHEET = [[WORKER_DOWN, WORKER_UP, WORKER_LEFT]]
NAMES = [["worker_down", "worker_up", "worker_left"]]
GUARD_SHEET = [[GUARD_DOWN, GUARD_UP, GUARD_LEFT]]
GUARD_NAMES = [["guard_down", "guard_up", "guard_left"]]

# Keep the human silhouette and every facing pixel-for-pixel identical to the
# established worker. The palette swap reads as a tied headscarf, red blouse,
# and practical apron without introducing a larger or more detailed person.
_MARKET_COLORS = str.maketrans({"H": "K", "O": "R", "o": "r", "B": "C"})
MARKET_SHEET = [[
    WORKER_DOWN.translate(_MARKET_COLORS),
    WORKER_UP.translate(_MARKET_COLORS),
    WORKER_LEFT.translate(_MARKET_COLORS),
]]
MARKET_NAMES = [["market_down", "market_up", "market_left"]]


def main() -> None:
    npcs = (
        Path(__file__).resolve().parents[1] / "assets" / "sprites" / "npcs"
    )
    npcs.mkdir(parents=True, exist_ok=True)
    for name, sheet, names in (
        ("dock_worker", SHEET, NAMES),
        ("guard", GUARD_SHEET, GUARD_NAMES),
        ("market_woman", MARKET_SHEET, MARKET_NAMES),
    ):
        out = npcs / f"{name}.png"
        render_sheet(sheet, names, FRAME_W, FRAME_H, PALETTE).save(out)
        print(f"Wrote {out}")


if __name__ == "__main__":
    main()
